### ISSUE TITLE
Extract more commit properties

### ISSUE THREAD

**Issue by jbon** [jbon/Github-Social-Network-Analysis#3]
...and store them as a node attribute
How to do this: 

In the header of the XML tree, add:
`
SubElement(graphml, 'key', { 
    "for":"node", 
    "id":"<anyUniqueId>", 
    "attr.name":"<AttrName>", 
    "attr.type":"<dataType>"})
`
And in the XML node description, add:
```
attributeData = SubElement(node, "data", {"key":"<attrName>"})
attributeData.text = <DataContent>
```

Example of commit property to extract: [github.GitCommit.GitCommit.date](http://pygithub.readthedocs.io/en/latest/github_objects/GitCommit.html#github.GitCommit.GitCommit)

Extract all data that may help further analysis of the commit network

**Comment by kerstinopen** [comment]
I included the commit url and information about the comments on commits.
Up to now, the script can extract the body, date of creation and creator of comments on commits, but it would be possible to extract more (https://developer.github.com/v3/repos/comments/), I`m not sure if that`s necessary, what do you think?

**Comment by kerstinopen** [comment]
( see  pull request "Update #2 branch-network-mining.py")

**Comment by jbon** [comment]
Property github.GitCommit.GitCommit.date isn't extracted for the moment

**Comment by jbon** [comment]
http://stackoverflow.com/questions/14909110/github-api-for-python-pygithub-get-a-list-of-all-commits-for-a-particular-re
https://github.com/PyGithub/PyGithub/issues/54

**Comment by jbon** [comment]
added extraction of currentCommit.commit.committer.date
